### ISSUE TITLE
Mistake in exercise 1, section 6.5

### ISSUE THREAD

**Issue by Lucifer-02** [PredictioNN/high_school_intro_data_science_course#1]
Original: "Explain the difference between an absolute path and a relative path. Why is it preferable to use an **absolute path**?"

I think it must be **relative path**.

**Comment by PredictioNN** [comment]
Thanks very much for pointing this out. You are correct. I've added to the
book errata
<https://github.com/PredictioNN/intro_data_science_course/blob/main/book_materials/errata.md>
and updated the question
<https://github.com/PredictioNN/intro_data_science_course/blob/main/book_materials/solutions_to_exercises/ch06_data_processing.ipynb>
.

best,
A
